"""music table

Revision ID: 19ed1473de36
Revises: 5e627ebd0998
Create Date: 2024-06-25 00:58:15.691053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ed1473de36'
down_revision = '5e627ebd0998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gymnast_music',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gymnast_id', sa.Integer(), nullable=False),
    sa.Column('apparatus', sa.String(length=16), nullable=False),
    sa.Column('music_location', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['gymnast_id'], ['gymnast.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gymnast_music', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gymnast_music_gymnast_id'), ['gymnast_id'], unique=False)

    with op.batch_alter_table('gymnast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gymnast', schema=None) as batch_op:
        batch_op.drop_column('club')

    with op.batch_alter_table('gymnast_music', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gymnast_music_gymnast_id'))

    op.drop_table('gymnast_music')
    # ### end Alembic commands ###
