"""base

Revision ID: 5e627ebd0998
Revises: 
Create Date: 2024-06-25 00:36:27.465232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e627ebd0998'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gymnast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('surname', sa.String(length=128), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('age_group', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'surname')
    )
    with op.batch_alter_table('gymnast', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gymnast_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_gymnast_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_gymnast_surname'), ['surname'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gymnast', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gymnast_surname'))
        batch_op.drop_index(batch_op.f('ix_gymnast_name'))
        batch_op.drop_index(batch_op.f('ix_gymnast_level'))

    op.drop_table('gymnast')
    # ### end Alembic commands ###
